/* #define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RIGHT_CTRL

// Neutralize left alt, left GUI, right GUI and left Control+Shift
#define MODS_TO_NEUTRALIZE { MOD_BIT(KC_LEFT_ALT), MOD_BIT(KC_LEFT_GUI), MOD_BIT(KC_RIGHT_GUI), MOD_BIT(KC_LEFT_CTRL)|MOD_BIT(KC_LEFT_SHIFT) } */

#define TAPPING_TERM 200
#define RETRO_TAPPING 

// #define AUTO_SHIFT_TIMEOUT 150
// #define RETRO_SHIFT 600
// #define QUICK_TAP_TERM 0
// #define PERMISSIVE_HOLD


#define MASTER_RIGHT
#define RGBLIGHT_SLEEP