#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RIGHT_CTRL
#define MODS_TO_NEUTRALIZE { MOD_BIT(KC_LEFT_ALT), MOD_BIT(KC_LEFT_GUI), MOD_BIT(KC_RIGHT_GUI), MOD_BIT(KC_LEFT_CTRL)|MOD_BIT(KC_LEFT_SHIFT), MOD_BIT(KC_LEFT_CTRL) }

#define TAPPING_TERM 250
#define RETRO_TAPPING

#define AUTO_SHIFT_TIMEOUT 200
#define RETRO_SHIFT
#define QUICK_TAP_TERM 0
#define PERMISSIVE_HOLD


#define MASTER_RIGHT
#define RGBLIGHT_SLEEP