#define UOSA UNDO_OS_AWARE
#define CTOA  CUT_OS_AWARE
#define CPOA COPY_OS_AWARE
#define POSA  PASTE_OS_AWARE
#define FOSA  FIND_OS_AWARE
#define HOSA HOME_OS_AWARE
#define EOSA END_OS_AWARE

#define CYCL KC_CYCLE_LAYERS

#define LGUI_MT_S LGUI_T(KC_S)

#define LCTL_MT_N LCTL_T(KC_N)
#define RCTL_MT_I RCTL_T(KC_I)

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RIGHT_CTRL
#define MODS_TO_NEUTRALIZE { MOD_BIT(KC_LEFT_ALT), MOD_BIT(KC_LEFT_GUI), MOD_BIT(KC_RIGHT_GUI), MOD_BIT(KC_LEFT_CTRL)|MOD_BIT(KC_LEFT_SHIFT), MOD_BIT(KC_LEFT_CTRL) }

#define TAPPING_TERM 210
#define RETRO_TAPPING

#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_TIMEOUT 200
#define RETRO_SHIFT
#define QUICK_TAP_TERM 0
#define PERMISSIVE_HOLD

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_OLED_ENABLE

#define MASTER_RIGHT
#define RGBLIGHT_SLE